Pages/CardsCollection.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectWeeb
{
    public class CardsCollectionModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Connexion.cshtml.cs
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using LiteDB.Engine;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.TagHelpers;
using Microsoft.AspNetCore.SignalR.Client;
using Newtonsoft.Json;
using ProjectWeeb.GameCard.Business.BusinessData;
using ProjectWeeb.GameCard.Control;
using ProjectWeeb.GameCard.Manager;

namespace ProjectWeeb.Pages
{
    public class ConnectionModel : PageModel
    {
        public void OnGet()
        {
            
        }

        public async Task<IActionResult> OnPost()
        {
            string login = Request.Form["login"];
            string password = Request.Form["password"];
            
            User user = CWebSite.GetInstance().WebSiteManager.UserController.TryLogUser(login, password);
            if (user != null)
            {
                string s = JsonConvert.SerializeObject(user);

                HttpContext.Session.SetString("user",s);

                Response.Redirect("/Profile");
            }
            else
            {
                
                return RedirectToPage("Connexion", "idInfo", new { idInfo = 4});
            }

            return null;
        }
    }
}

Pages/DecksCollection.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectWeeb
{
    public class DeckCollectionModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Encyclopedia.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectWeeb
{
    public class EncyclopediaModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ProjectWeeb.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/GamePlateau.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectWeeb.Pages
{
    public class GamePlateauModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using ProjectWeeb.GameCard.Control;
using ProjectWeeb.GameCard.Manager;

namespace ProjectWeeb.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Inscription.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectWeeb.GameCard.Control;

namespace ProjectWeeb.Pages
{
    public class InscriptionModel : PageModel
    {
        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost()
        {
            string login = Request.Form["login"];
            string password = Request.Form["password"];
            string confpassword = Request.Form["confPassword"];
            if (confpassword.Equals(password))
            {
                var result = CWebSite.GetInstance().WebSiteManager.UserController.TryRegisterUser(login, password);

                if (result)
                {
                    return RedirectToPage("Connexion", "idInfo", new { idInfo = 3 });
                }
                else
                {
                    return RedirectToPage("Inscription", "idInfo", new { idInfo = 2 });
                }
            }
            else
            {
                return RedirectToPage("Inscription", "idInfo", new { idInfo = 1 });
            }
        }
    }
}

Pages/Lolo/Connection.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectWeeb.Pages.Lolo
{
    public class ConnectionModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ProjectWeeb.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Profile.cshtml.cs
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using ProjectWeeb.GameCard.Business.BusinessData;
using ProjectWeeb.GameCard.Control;

namespace ProjectWeeb.Pages
{
    public class ProfileModel : PageModel
    {
        public void OnGet()
        {
            string s = HttpContext.Session.GetString("user");

            if (s == null || s.Equals(""))
            {
                Response.Redirect("/Connexion");
            }
        }

        public int UserId { get; set; }
        
        public async Task<IActionResult> OnPostGamePlateau()
        {
            string s = HttpContext.Session.GetString("user");
            User user = JsonConvert.DeserializeObject<User>(s);
            string idGame = null;

            while (idGame == null)
            {
                idGame = CWebSite.GetInstance().GameManager.ConnectPlayerToGame(user);
                if (idGame == null)
                {
                    Thread.Sleep(1000);
                }
            }

            return RedirectToPage("GamePlateau", "ids", new {gameId = idGame, userId = user.Id});
        }
    }
}

Pages/CardsCollection.cshtml
@page
@using System.IO
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@using ProjectWeeb.GameCard.Business.BusinessData
@using ProjectWeeb.GameCard.Helper
@using ProjectWeeb.GameCard.Manager
@model ProjectWeeb.CardsCollectionModel
@{
    ViewData["Title"] = "CardsCollection";
}
<div class="container2">
    <div id="background">
        <img src="~/src/Background3.png" class="stretch" alt="" />
    </div>

    <div id="Corner">
        @{
            string s = HttpContext.Session.GetString("user");
            string name = "";
            if (!string.IsNullOrEmpty(s))
            {
                User user = JsonConvert.DeserializeObject<User>(s);
                name = user.UserName;
            }

            <h2>@name</h2>
        }
    </div>

    <div id="ImgCollect">
        @{
            if (!string.IsNullOrEmpty(s))
            {
                User user = JsonConvert.DeserializeObject<User>(s);

                foreach (var card in user.Cards)
                {

                    string path = WeebResourceManager.GetInstance().GetCardImageByCardId(card.CardId);
                    <img src=@path class="image">
                }
            }
        }
    </div>

</div>

Pages/Connexion.cshtml
@page
@model ProjectWeeb.Pages.ConnectionModel
@{
    <script src="js/error.js"></script>

    <div class="container">

        <div id="background">
            <img src="/src/Accueil_background.png" class="stretch" alt="" />
        </div>

        <form method="post" class="Form" id="connectionForm">
            <label for="login">Username</label>
            <input type="text" name="login" id="login" required />
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required />
            <input type="submit" value="Submit" class="Button_submit" />
        </form>
    </div>

}

Pages/DecksCollection.cshtml
@page
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@using ProjectWeeb.GameCard.Business.BusinessData
@using ProjectWeeb.GameCard.Manager
@model ProjectWeeb.DeckCollectionModel
@{
    ViewData["Title"] = "DeckCollection";
}

    <div class="container2">
        <div id="background">
            <img src="~/src/Background3.png" class="stretch" alt="" />
        </div>

        <div id="Corner">
            @{
                string s = HttpContext.Session.GetString("user");
                string name = "";
                if (!string.IsNullOrEmpty(s))
                {
                    User user = JsonConvert.DeserializeObject<User>(s);
                    name = user.UserName;
                }

                <h2>@name</h2>
            }
        </div>

        <div id="ImgCollect">
            @{
                if (!string.IsNullOrEmpty(s))
                {
                    User user = JsonConvert.DeserializeObject<User>(s);

                    foreach (var card in user.Cards)
                    {

                        string path = WeebResourceManager.GetInstance().GetCardImageByCardId(card.CardId);
                        <img src=@path class="image">
                    }
                }

            }
        </div>

    </div>

Pages/Encyclopedia.cshtml
@page
@model ProjectWeeb.EncyclopediaModel
@{
    <div class="container2">
        <div id="background">
            <img src="~/src/Background3.png" class="stretch" alt="" />
        </div>

        <div id="Corner">
            <!--Put img as background in css, get Username and Level/rnk from DB-->
            level
        </div>

        <div id="Encyclo">
            <img src="~/src/Cards/0.png" />
            <div>
                <h2>Megumin</h2>
                <br/>
                <p> Description</p>
            </div>
        </div>

    </div>
}

Pages/GamePlateau.cshtml
@page
@using ProjectWeeb.GameCard.Control
@model ProjectWeeb.Pages.GamePlateauModel
@{
    <style>
        body {
            overflow: hidden;
        }
    </style>
    <div class="container2">
        <canvas id="Canvas">
        </canvas>
    </div>
    
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/weeb.js"></script>
}

Pages/Index.cshtml
@page
@model ProjectWeeb.Pages.IndexModel
<div class="container">
    <div id="background">
        <img src="/src/Accueil_background.png" class="stretch" alt="" />
    </div>
    
    <a asp-area="" asp-page="/Inscription" class="Button">Inscription</a>

    <img  src="~/src/logo_weeb.png" />

    <a asp-area="" asp-page="/Connexion" class="Button">Connection</a>
</div>

Pages/Inscription.cshtml
@page
@model ProjectWeeb.Pages.InscriptionModel
@{
    <script src="js/error.js"></script>

    <div class="container">
        <div id="background">
            <img src="/src/Accueil_background.png" class="stretch" alt="" />
        </div>

        <form method="POST" class="Form" id="inscriptionForm">
            <label for="login">Username</label>
            <input type="text" name="login" id="login" maxlength="18" required />
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required />
            <label for="confPassword">Confirm Password</label>
            <input type="password" name="confPassword" id="confPassword" minlength="4" required />
            <input type="submit" value="Submit" class="Button_submit" />
        </form>
    </div>
}

Pages/Profile.cshtml
@page
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@using ProjectWeeb.GameCard.Business.BusinessData
@using ProjectWeeb.GameCard.Control
@model ProjectWeeb.Pages.ProfileModel
@{
    <div class="container2">
        <div id="background">
            <img src="~/src/Background2.png" class="stretch" alt="" />
        </div>

        <!--Left top level corner -->
        <div id="Corner">
            @{
                string s = HttpContext.Session.GetString("user");
                string name = "";
                if (!string.IsNullOrEmpty(s))
                {
                    User user = JsonConvert.DeserializeObject<User>(s);
                    name = user.UserName;
                }

                <h2>@name</h2>
            }
        </div>
        
        <div id="profileMenu">
            <form asp-page-handler="GamePlateau" method="post">
                <button id="PopUP" class="profileButton">Game</button>
            </form>

            <a asp-area="" asp-page="/CardsCollection" class="profileButton">Cards</a>

            <a asp-area="" asp-page="/DecksCollection" class="profileButton">Decks</a>
        </div>
        
    </div>
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectWeeb </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <noscript>
        <strong> Website Down for Maintenance </strong>
    </noscript>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>